blank_issues_enabled: false
contact_links:
  - name: Amplify UI Component Issue?
    url: https://github.com/aws-amplify/amplify-ui/issues/new/choose
    about: Open an issue in the Amplify-UI repository
    
